name: actions/setup-java
description: actions/setup-java
inputs:
  distribution:
    description: Java distribution
    required: false
    default: temurin
  java-version:
    description: Java version
    required: true
  cache:
    description: Cache
    required: false
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v2.5.0
      with:
        architecture: x64
        cache: ${{ inputs.cache && 'maven' || null }}
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version}}