version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels: []
    assignees: [Katsute]
    schedule:
      interval: daily
      time: '07:00'
      timezone: US/Eastern
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /actions/artifact/download
    labels: []
    assignees: [Katsute]
    schedule:
      interval: daily
      time: '07:00'
      timezone: US/Eastern
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /actions/artifact/upload
    labels: []
    assignees: [Katsute]
    schedule:
      interval: daily
      time: '07:00'
      timezone: US/Eastern
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /actions/checkout
    labels: []
    assignees: [Katsute]
    schedule:
      interval: daily
      time: '07:00'
      timezone: US/Eastern
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /actions/codeql
    labels: []
    assignees: [Katsute]
    schedule:
      interval: daily
      time: '07:00'
      timezone: US/Eastern
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /actions/codeql/analyze
    labels: []
    assignees: [Katsute]
    schedule:
      interval: daily
      time: '07:00'
      timezone: US/Eastern
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /actions/commit
    labels: []
    assignees: [Katsute]
    schedule:
      interval: daily
      time: '07:00'
      timezone: US/Eastern
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /actions/java
    labels: []
    assignees: [Katsute]
    schedule:
      interval: daily
      time: '07:00'
      timezone: US/Eastern
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /actions/java/compile
    labels: []
    assignees: [Katsute]
    schedule:
      interval: daily
      time: '07:00'
      timezone: US/Eastern
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /actions/java/exec
    labels: []
    assignees: [Katsute]
    schedule:
      interval: daily
      time: '07:00'
      timezone: US/Eastern
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /actions/java/package
    labels: []
    assignees: [Katsute]
    schedule:
      interval: daily
      time: '07:00'
      timezone: US/Eastern
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /actions/java/test
    labels: []
    assignees: [Katsute]
    schedule:
      interval: daily
      time: '07:00'
      timezone: US/Eastern
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /actions/node
    labels: []
    assignees: [Katsute]
    schedule:
      interval: daily
      time: '07:00'
      timezone: US/Eastern
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /actions/node/install
    labels: []
    assignees: [Katsute]
    schedule:
      interval: daily
      time: '07:00'
      timezone: US/Eastern
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /actions/node/rebuild
    labels: []
    assignees: [Katsute]
    schedule:
      interval: daily
      time: '07:00'
      timezone: US/Eastern
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /actions/node/test
    labels: []
    assignees: [Katsute]
    schedule:
      interval: daily
      time: '07:00'
      timezone: US/Eastern
    open-pull-requests-limit: 99
