name: mvn package
description: mvn package
inputs:
  args:
    description: Arguments
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: mvn package -DskipTests --no-transfer-progress ${{ inputs.args }}