name: actions/upload-artifact
description: actions/upload-artifact
inputs:
  name:
    description: Artifact name
    required: true
  path:
    description: Artifact path
    required: true
  retention:
    description: Retention in days
    required: false
    default: 1
runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        retention-days: ${{ inputs.retention }}