name: mvn exec
description: mvn exec
inputs:
  args:
    description: Arguments
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: mvn exec:java -DskipTests --no-transfer-progress ${{ inputs.args }}