name: git push
description: git push
inputs:
  name:
    description: Git username
    required: true
  email:
    description: Git email
    required: true
  files:
    description: Files to commit; comma separated
    required: true
  message:
    description: Commit message
    required: false
    default: Commit files
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        git config --global user.name "${{ inputs.name }}"
        git config --global user.email "${{ inputs.email }}"
        git add "${{ join(fromJSON(format('[{0}]', inputs.files)), '" "') }}"
        git diff-index --quiet HEAD || git commit -m "${{ inputs.message }}"
        git push