name: JUnit Report
description: Generate JUnit report
inputs:
  token:
    description: Checkout token
    required: true
  path:
    description: Sources path
    default: .
    required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        repository: Katsute/JUnit-Report
        ref: 2426c10364e67bb5b103bf7ad9205b3f67702ca3
        path: ./.github/junit-report
        token: ${{ inputs.token }}

    - uses: ./.github/junit-report
      with:
        path: ${{ inputs.path }}
