name: JUnit Report
description: Generate JUnit report
inputs:
  token:
    description: Checkout token
    required: true
  path:
    description: Sources path
    default: .
    required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        repository: Katsute/JUnit-Report
        ref: 5c7b90f5641f550409ffc3463f9bbe399d0d98ac
        path: ./.github/junit-report
        token: ${{ inputs.token }}

    - uses: ./.github/junit-report
      with:
        path: ${{ inputs.path }}
