name: JUnit Report
description: Generate JUnit report
inputs:
  token:
    description: Checkout token
    required: true
  path:
    description: Sources path
    default: .
    required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        repository: Katsute/JUnit-Report
        ref: 4ca5f9611f770df53df78d64d02d3af38caa54b6
        path: ./.github/junit-report
        token: ${{ inputs.token }}

    - uses: ./.github/junit-report
      with:
        path: ${{ inputs.path }}