name: actions/setup-node
description: actions/setup-node
inputs:
  node-version:
    description: Node version
    required: true
  cache:
    description: Cache
    required: false
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        architecture: x64
        cache: ${{ inputs.cache && 'npm' || null }}
        node-version: ${{ inputs.node-version }}