name: Java Exec

on:
  workflow_call:
    inputs:
      os:
        type: string
        default: ubuntu-latest
        required: false
        description: The operating system
      timeout:
        type: number
        default: 60
        required: false
        description: Job timeout in minutes

      java-version:
        type: string
        default: 17
        required: false
        description: The Java version to use

      compile-pre:
        type: string
        required: false
        description: Command to run before compile
      compile-args:
        type: string
        required: false
        description: Arguments for `mvn compile`
      compile-post:
        type: string
        required: false
        description: Command to run after compile

      exec-pre:
        type: string
        required: false
        description: Command to run before exec
      exec-args:
        type: string
        required: false
        description: Arguments for `mvn exec`
      exec-post:
        type: string
        required: false
        description: Command to run after exec

      command-pre:
        type: string
        required: false
        description: Command to run before exec
      command-post:
        type: string
        required: false
        description: Command to run after exec

      artifact-name:
        type: string
        default: artifact
        required: false
        description: Artifact name
      artifact-path:
        type: string
        required: false
        description: Artifact path

      git-name:
        type: string
        required: false
        default: github-actions[bot]
        description: The username to commit with
      git-email:
        type: string
        required: false
        default: github-actions[bot]@users.noreply.github.com
        description: The email to commit with
      commit-files:
        type: string
        required: false
        description: The file or list of files to commit
      commit-message:
        type: string
        default: Commit files
        required: false
        description: Commit message

    secrets:
      compile-pre:
        required: false
      compile-post:
        required: false
      exec-pre:
        required: false
      exec-args:
        required: false
      exec-post:
        required: false
      # @deprecated
      command-pre:
        required: false
      command-post:
        required: false

jobs:
  Exec:
    name: Exec (Java ${{ inputs.java-version }})
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: 📤 Checkout Repository
        uses: Katsute/Workflows/Actions/checkout@main

      - name: ☕ Install Java
        uses: Katsute/Workflows/Actions/java@main
        with:
          java-version: ${{ inputs.java-version }}

      - name: ✔️ Pre Compile
        run: ${{ inputs.compile-pre || secrets.compile-pre }}

      - name: ✔️ Compile with Maven
        uses: Katsute/Workflows/Actions/java/compile@main
        with:
          args: ${{ inputs.compile-args }}

      - name: ✔️ Post Compile
        run: ${{ inputs.compile-post || secrets.compile-post }}

      - name: ✔️ Pre Exec
        run: |
          ${{ inputs.exec-pre || secrets.exec-pre || inputs.command-pre || secrets.command-pre }}

      - name: ✔️ Exec with Maven
        uses: Katsute/Workflows/Actions/java/exec@main
        with:
          args: ${{ inputs.exec-args || secrets.exec-args }}

      - name: ✔️ Post Exec
        run: |
          ${{ inputs.exec-post || secrets.exec-post || inputs.command-post || secrets.command-post }}

      - name: 🚀 Upload Artifact
        if: inputs.artifact-name && inputs.artifact-path
        uses: Katsute/Workflows/Actions/artifact/upload@main
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention: 1

      - name: 📥 Commit Changes
        if: inputs.commit-files
        uses: Katsute/Workflows/Actions/commit@main
        with:
          name: ${{ inputs.git-name }}
          email: ${{ inputs.git-email }}
          files: ${{ inputs.commit-files }}
          message: ${{ inputs.commit-message }}