name: Generate Javadoc

on:
  workflow_call:
    inputs:
      os:
        type: string
        default: ubuntu-latest
        required: false
        description: The operating system
      timeout:
        type: number
        default: 30
        required: false
        description: Job timeout in minutes
      java-version:
        type: number
        default: 17
        required: false
        description: The Java version to use
      package-args:
        type: string
        required: false
        description: Arguments for `mvn package`

jobs:
  javadoc:
    name: Generate Javadoc (Java ${{ inputs.java-version }})
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v2.3.5

      - name: ☕ Install Java
        uses: actions/setup-java@v2.3.1
        with:
          architecture: x64
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: 📦 Package with Maven
        run: mvn package -DskipTests --no-transfer-progress ${{ inputs.package-args }}

      - name: 🚀 Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: javadoc
          path: target/*-javadoc.jar
          retention-days: 1