name: Java Exec

on:
  workflow_call:
    inputs:
      os:
        type: string
        default: ubuntu-latest
        required: false
        description: The operating system
      timeout:
        type: number
        default: 60
        required: false
        description: Job timeout in minutes

      java-version:
        type: string
        default: 17
        required: false
        description: The Java version to use

      compile-pre:
        type: string
        required: false
        description: Command to run before compile
      compile-args:
        type: string
        required: false
        description: Arguments for `mvn compile`
      compile-post:
        type: string
        required: false
        description: Command to run after compile

      exec-pre:
        type: string
        required: false
        description: Command to run before exec
      exec-args:
        type: string
        required: false
        description: Arguments for `mvn exec`
      exec-post:
        type: string
        required: false
        description: Command to run after exec

      artifact-name:
        type: string
        default: artifact
        required: false
        description: Artifact name
      artifact-path:
        type: string
        required: false
        description: Artifact path

      git-name:
        type: string
        required: false
        default: github-actions[bot]
        description: The username to commit with
      git-email:
        type: string
        required: false
        default: github-actions[bot]@users.noreply.github.com
        description: The email to commit with
      commit-files:
        type: string
        required: false
        description: The file or list of files to commit
      commit-message:
        type: string
        default: Commit files
        required: false
        description: Commit message

    secrets:
      compile-pre:
        required: false
      compile-post:
        required: false
      exec-pre:
        required: false
      exec-args:
        required: false
      exec-post:
        required: false

jobs:
  Exec:
    name: Exec (Java ${{ inputs.java-version }})
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v3

      - name: ☕ Install Java
        uses: actions/setup-java@v3
        with:
          architecture: x64
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: ✔️ Pre Compile
        run: ${{ inputs.compile-pre || secrets.compile-pre }}

      - name: ✔️ Compile with Maven
        env:
          args: ${{ inputs.compile-args }}
        run: mvn compile -DskipTests --no-transfer-progress $args

      - name: ✔️ Post Compile
        run: ${{ inputs.compile-post || secrets.compile-post }}

      - name: ✔️ Pre Exec
        run: |
          ${{ inputs.exec-pre || secrets.exec-pre }}

      - name: ✔️ Exec with Maven
        env:
          args: ${{ inputs.exec-args || secrets.exec-args }}
        run: mvn exec:java -DskipTests --no-transfer-progress $args

      - name: ✔️ Post Exec
        run: |
          ${{ inputs.exec-post || secrets.exec-post }}

      - name: 🚀 Upload Artifact
        if: inputs.artifact-name && inputs.artifact-path
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: 1

      - name: 📥 Commit Changes
        if: inputs.commit-files
        env:
          name: ${{ inputs.git-name }}
          email: ${{ inputs.git-email }}
          files: ${{ join(fromJSON(format('[{0}]', inputs.commit-files)), '" "') }}
          message: ${{ inputs.commit-message }}
        run: |
          git config --global user.name "$name"
          git config --global user.email "$email"
          git add "$files"
          git diff-index --quiet HEAD || git commit -m "$message"
          git push