name: Java Package Commit
on:
  workflow_call:
    inputs:
      os:
        type: string
        default: ubuntu-latest
        required: false
        description: The operating system
      timeout:
        type: number
        default: 60
        required: false
        description: Job timeout in minutes
      java-version:
        type: number
        default: 17
        required: false
        description: The Java version to use
      package-args:
        type: string
        required: false
        description: Arguments for `mvn package`
      command:
        type: string
        required: false
        description: Commands to run
      git-name:
        type: string
        required: false
        default: github-actions[bot]
        description: The username to commit with
      git-email:
        type: string
        required: false
        default: github-actions[bot]@users.noreply.github.com
        description: The email to commit with
      commit-files:
        type: string
        required: true
        description: The file or list of files to commit
      commit-message:
        type: string
        default: Commit files
        required: false
        description: Commit message

jobs:
  deploy:
    name: Deploy (Java ${{ inputs.java-version }})
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout }}
    environment: ${{ inputs.environment }}
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: ☕ Install Java
        uses: actions/setup-java@v2.3.1
        with:
          architecture: x64
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: ✔ Package with Maven
        run: mvn package -DskipTests --no-transfer-progress ${{ inputs.package-args }}

      - name: ✔ Run Command
        if: inputs.command
        run: |
          ${{ inputs.command }}

      - name: 📥 Commit Changes
        run: |
          git config --global user.name "${{ inputs.git-name }}"
          git config --global user.email "${{ inputs.git-email }}"
          git add "${{ join(fromJSON(format('[{0}]', inputs.commit-files)), '" "') }}"
          git diff-index --quiet HEAD || git commit -m "${{ inputs.commit-message }}"
          git push