name: Java Exec

on:
  workflow_call:
    inputs:
      os:
        type: string
        default: ubuntu-latest
        required: false
      timeout:
        type: number
        default: 60
        required: false

      java-version:
        type: number
        default: 21
        required: false

      compile-pre:
        type: string
        required: false
      compile-args:
        type: string
        required: false
      compile-post:
        type: string
        required: false

      exec-pre:
        type: string
        required: false
      exec-args:
        type: string
        required: false
      exec-post:
        type: string
        required: false

      artifact-name:
        type: string
        default: artifact
        required: false
      artifact-path:
        type: string
        required: false

      git-name:
        type: string
        required: false
        default: github-actions[bot]
      git-email:
        type: string
        required: false
        default: github-actions[bot]@users.noreply.github.com
      commit-files:
        type: string
        required: false
      commit-message:
        type: string
        default: Commit files
        required: false

    secrets:
      compile-pre:
        required: false
      compile-post:
        required: false
      exec-pre:
        required: false
      exec-args:
        required: false
      exec-post:
        required: false

jobs:
  Exec:
    name: Exec (Java ${{ inputs.java-version }})
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          architecture: x64
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Pre Compile
        run: ${{ inputs.compile-pre || secrets.compile-pre }}

      - name: Compile with Maven
        env:
          args: ${{ inputs.compile-args }}
        run: mvn compile -DskipTests --no-transfer-progress $args

      - name: Post Compile
        run: ${{ inputs.compile-post || secrets.compile-post }}

      - name: Pre Exec
        run: |
          ${{ inputs.exec-pre || secrets.exec-pre }}

      - name: Exec with Maven
        env:
          args: ${{ inputs.exec-args || secrets.exec-args }}
        run: mvn exec:java -DskipTests --no-transfer-progress $args

      - name: Post Exec
        run: |
          ${{ inputs.exec-post || secrets.exec-post }}

      - name: Upload Artifact
        if: inputs.artifact-name && inputs.artifact-path
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: 1
          compression-level: 9

      - name: Commit Changes
        if: inputs.commit-files
        env:
          name: ${{ inputs.git-name }}
          email: ${{ inputs.git-email }}
          files: ${{ join(fromJSON(format('[{0}]', inputs.commit-files)), '" "') }}
          message: ${{ inputs.commit-message }}
        run: |
          git config --global user.name "$name"
          git config --global user.email "$email"
          git add "$files"
          git diff-index --quiet HEAD || git commit -m "$message"
          git push