name: Repository Manager
on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  manager:
    name: Repository Manager
    uses: Katsute/Repository-Manager/.github/workflows/repository-manager.yml@fb88ac1f0b9292368780c2d7bd96508530f58053
    if: >-
      ${{
      (github.repository_owner == 'Katsute' || github.repository_owner == 'KatsuteDev') &&
      github.repository != 'Katsute/Repository-Manager' &&
      github.actor != 'mashiro-san' &&
      !endsWith(github.actor, '[bot]')
      }}
    with:
      login: mashiro-san
      username: Mashiro
      email: 107276926+mashiro-san@users.noreply.github.com
    secrets:
      token: ${{ secrets.token || secrets.GITHUB_TOKEN }}