name: Repository Manager
on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  manager:
    name: Repository Manager
    uses: Katsute/Manager/.github/workflows/manager.yml@cca13273a26f758f5e0cac78deeced871376eff9
    if: >-
      ${{
      (github.repository_owner == 'Katsute' || github.repository_owner == 'KatsuteDev') &&
      github.repository != 'Katsute/Manager' &&
      github.actor != 'mashiro-san' &&
      !endsWith(github.actor, '[bot]')
      }}
    with:
      login: mashiro-san
      username: Mashiro
      email: 107276926+mashiro-san@users.noreply.github.com
    secrets:
      token: ${{ secrets.token || secrets.GITHUB_TOKEN }}