name: npm Commit

on:
  workflow_call:
    inputs:
      os:
        type: string
        default: ubuntu-latest
        required: false
        description: The operating system
      timeout:
        type: number
        default: 30
        required: false
        description: Job timeout in minutes
      node-version:
        type: number
        default: 14
        required: false
        description: The NodeJS version to use
      command:
        type: string
        required: false
        description: Commands to run
      git-name:
        type: string
        required: false
        default: github-actions[bot]
        description: The username to commit with
      git-email:
        type: string
        required: false
        default: github-actions[bot]@users.noreply.github.com
        description: The email to commit with
      commit-files:
        type: string
        required: true
        description: The file or list of files to commit
      commit-message:
        type: string
        default: Commit files
        required: false
        description: Commit message
    secrets:
      command:
        required: false

jobs:
  Commit:
    name: Run & Commit (${{ inputs.os }} / Node ${{ inputs.node-version }})
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v2.3.5

      - name: 📚 Install npm
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ inputs.node-version }}
          architecture: x64
          cache: npm

      - name: ✔ Run Command
        if: inputs.command
        run: |
          ${{ inputs.command }}

      - name: ✔ Run Command (secrets)
        if: ${{ !inputs.command }}
        run: |
          ${{ secrets.command }}

      - name: 📥 Commit Changes
        run: |
          git config --global user.name "${{ inputs.git-name }}"
          git config --global user.email "${{ inputs.git-email }}"
          git add "${{ join(fromJSON(format('[{0}]', inputs.commit-files)), '" "') }}"
          git diff-index --quiet HEAD || git commit -m "${{ inputs.commit-message }}"
          git push
