name: npm Commit

on:
  workflow_call:
    inputs:
      os:
        type: string
        default: ubuntu-latest
        required: false
        description: The operating system
      timeout:
        type: number
        default: 30
        required: false
        description: Job timeout in minutes
      node-version:
        type: number
        default: 14
        required: false
        description: The NodeJS version to use
      command:
        type: string
        required: false
        description: Commands to run
      artifact-name:
        type: string
        default: artifact
        required: false
        description: Artifact name
      artifact-path:
        type: string
        required: true
        description: Artifact path
    secrets:
      command:
        required: false

jobs:
  Artifact:
    name: Run & Artifact (${{ inputs.os }} / Node ${{ inputs.node-version }})
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: 📚 Install npm
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ inputs.node-version }}
          architecture: x64
          cache: npm

      - name: ✔ Run Command
        if: inputs.command
        run: |
          ${{ inputs.command }}

      - name: ✔ Run Command (secrets)
        if: ${{ !inputs.command }}
        run: |
          ${{ secrets.command }}

      - name: 🚀 Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: 1
