name: Stale
on:
  workflow_call:
    secrets:
      token:
        required: false

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.token || secrets.GITHUB_TOKEN }}
          days-before-stale: 28
          days-before-close: 14
          stale-issue-message: This issue has been marked as stale due to inactivity.
          stale-pr-message: This pull request has been marked as stale due to inactivity.
          close-issue-message: This issue has been closed due to inactivity.
          close-pr-message: This pull request has been closed due to inactivity.
          stale-issue-label: stale
          stale-pr-label: stale
          operations-per-run: 100
          exempt-all-milestones: true
          exempt-all-assignees: true