name: Stale
on:
  workflow_call:
    secrets:
      token:
        required: false

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.token || secrets.GITHUB_TOKEN }}
          days-before-stale: 28
          days-before-close: 14
          stale-issue-message: This issue has been marked as stale because there has been no activity in the last 30 days. This issue will be closed in 14 days if there is no new activity. <br><br> <sub>This is an automated message, do not reply to this comment.</sub>
          stale-pr-message: This pull request has been marked as stale because there has been no activity in the last 30 days. This pull request will be closed in 14 days if there is no new activity. <br><br> <sub>This is an automated message, do not reply to this comment.</sub>
          close-issue-message: This issue has been closed because there has been no activity in the last 45 days. Open a new issue if not resolved. <br><br> <sub>This is an automated message, do not reply to this comment.</sub>
          close-pr-message: This pull request has been closed because there has been no activity in the last 45 days. Open a new pull request if not resolved. <br><br> <sub>This is an automated message, do not reply to this comment.</sub>
          stale-issue-label: stale
          stale-pr-label: stale
          operations-per-run: 100
          exempt-all-milestones: true
          exempt-all-assignees: true
  lock:
    name: Lock Stale Issues
    runs-on: ubuntu-latest
    if: (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'stale')) || (github.event_name == 'pull_request' && contains( github.event.pull_request.labels.*.name, 'stale'))
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token || secrets.GITHUB_TOKEN }}

      - name: Issue Lock
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.token || secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue && 'issue' || 'pr' }}
          NUMBER: ${{ github.event.issue && github.event.issue.number || github.event.pull_request.number }}
        run: gh $ISSUE lock $NUMBER